---
- name: Create service account for Papertrail
  user: name=papertrail
        system=yes
        home=/var/lib/papertrail
        shell=/bin/false
        state=present

- name: Download Papertrail PEM
  get_url: url="https://papertrailapp.com/tools/papertrail-bundle.pem"
           dest="/etc/papertrail-bundle.pem"
           checksum="sha256:7019189e20ed695e9092e67d91a3b37249474f4c4c6355193ce6d2cb648f147c"
           mode=0644

- name: Install TLS support for Rsyslog
  apt: name=rsyslog-gnutls state=present

- name: Download remote_syslog
  get_url: url="https://github.com/papertrail/remote_syslog2/releases/download/v{{ papertrail_version }}/remote_syslog_linux_amd64.tar.gz"
           dest="/usr/local/src/remote_syslog_{{ papertrail_version }}_linux_amd64.tar.gz"
  register: remote_syslog_download

- include: extract-remote-syslog.yml
  when: remote_syslog_download.changed

- name: Configure Rsyslog to use Papertrail
  template: src="90-papertrail.conf.j2"
            dest="/etc/rsyslog.d/90-papertrail.conf"
  notify:
    - Restart Rsyslog

- debug: msg="Adding papertrail config at {{ papertrail_remote_syslog_config_paths[ansible_service_mgr].path }}"

- name: Configure Papertrail service definition
  template: src="remote_syslog.{{ ansible_service_mgr }}.conf.j2"
            dest="{{ papertrail_remote_syslog_config_paths[ansible_service_mgr].path }}"

- name: Enable Papertrail service
  service: name=remote_syslog enabled=true
  notify:
    - Restart remote_syslog
