---
- name: Create service account for Papertrail
  user: name=papertrail
        system=yes
        home=/var/lib/papertrail
        shell=/bin/false
        state=present

- name: Download Papertrail PEM
  get_url: url="https://papertrailapp.com/tools/papertrail-bundle.pem"
           dest="/etc/papertrail-bundle.pem"
           sha256sum="c03a504397dc45b4fc05f978dbf02129793cbd2a0b64856c2ba1bb49a3b9aacb"
           mode=0644

- name: Install TLS support for Rsyslog
  apt: name=rsyslog-gnutls state=present

- name: Download remote_syslog
  get_url: url="https://github.com/papertrail/remote_syslog2/releases/download/v{{ papertrail_version }}/remote_syslog_linux_amd64.tar.gz"
           dest="/usr/local/src/remote_syslog_{{ papertrail_version }}_linux_amd64.tar.gz"

- name: Extract remote_syslog
  unarchive: src="/usr/local/src/remote_syslog_{{ papertrail_version }}_linux_amd64.tar.gz"
             dest=/opt
             copy=no
             owner=root
             group=root
             creates=/opt/remote_syslog/remote_syslog

- name: Configure Rsyslog to use Papertrail
  template: src="90-papertrail.conf.j2"
            dest="/etc/rsyslog.d/90-papertrail.conf"
  notify:
    - Restart Rsyslog

- name: Configure Papertrail service definition
  template: src="remote_syslog.conf.j2"
            dest="/etc/init/remote_syslog.conf"
  notify:
    - Restart remote_syslog
